/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Time = IDL.Int;
export const ProductVariant = IDL.Record({
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'subCategory' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'variants' : IDL.Vec(ProductVariant),
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const ReviewId = IDL.Nat;
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'variant' : ProductVariant,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'placed' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const CreditCardInfo = IDL.Record({
  'cvv' : IDL.Text,
  'expiry' : IDL.Text,
  'cardNumber' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'creditCard' : CreditCardInfo,
  'cashOnDelivery' : IDL.Null,
  'wallet' : IDL.Null,
});
export const OrderStatusHistory = IDL.Record({
  'status' : OrderStatus,
  'timestamp' : Time,
});
export const ShippingAddress = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'statusHistory' : IDL.Vec(OrderStatusHistory),
  'totalAmount' : IDL.Float64,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(CartItem),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Cart = IDL.Record({
  'userId' : IDL.Principal,
  'items' : IDL.Vec(CartItem),
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'userId' : IDL.Principal,
  'date' : Time,
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Wishlist = IDL.Record({
  'productIds' : IDL.Vec(ProductId),
  'userId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [ProductId], []),
  'addReview' : IDL.Func([ProductId, IDL.Nat, IDL.Text], [ReviewId], []),
  'addToCart' : IDL.Func([CartItem], [], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([IDL.Principal], [Cart], ['query']),
  'getOrder' : IDL.Func([OrderId], [Order], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getWishlist' : IDL.Func([IDL.Principal], [Wishlist], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Vec(CartItem), ShippingAddress, PaymentMethod, IDL.Float64],
      [OrderId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func([ProductId, Product], [], []),
  'upgrade' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Time = IDL.Int;
  const ProductVariant = IDL.Record({
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'subCategory' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'variants' : IDL.Vec(ProductVariant),
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ReviewId = IDL.Nat;
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'variant' : ProductVariant,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'placed' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const CreditCardInfo = IDL.Record({
    'cvv' : IDL.Text,
    'expiry' : IDL.Text,
    'cardNumber' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'creditCard' : CreditCardInfo,
    'cashOnDelivery' : IDL.Null,
    'wallet' : IDL.Null,
  });
  const OrderStatusHistory = IDL.Record({
    'status' : OrderStatus,
    'timestamp' : Time,
  });
  const ShippingAddress = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'statusHistory' : IDL.Vec(OrderStatusHistory),
    'totalAmount' : IDL.Float64,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(CartItem),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Cart = IDL.Record({
    'userId' : IDL.Principal,
    'items' : IDL.Vec(CartItem),
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'userId' : IDL.Principal,
    'date' : Time,
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Wishlist = IDL.Record({
    'productIds' : IDL.Vec(ProductId),
    'userId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [ProductId], []),
    'addReview' : IDL.Func([ProductId, IDL.Nat, IDL.Text], [ReviewId], []),
    'addToCart' : IDL.Func([CartItem], [], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([IDL.Principal], [Cart], ['query']),
    'getOrder' : IDL.Func([OrderId], [Order], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getWishlist' : IDL.Func([IDL.Principal], [Wishlist], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Vec(CartItem), ShippingAddress, PaymentMethod, IDL.Float64],
        [OrderId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func([ProductId, Product], [], []),
    'upgrade' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };