/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'userId' : Principal, 'items' : Array<CartItem> }
export interface CartItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'variant' : ProductVariant,
}
export interface CreditCardInfo {
  'cvv' : string,
  'expiry' : string,
  'cardNumber' : string,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'userId' : Principal,
  'createdAt' : Time,
  'statusHistory' : Array<OrderStatusHistory>,
  'totalAmount' : number,
  'shippingAddress' : ShippingAddress,
  'items' : Array<CartItem>,
}
export type OrderId = bigint;
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'outForDelivery' : null } |
  { 'placed' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface OrderStatusHistory {
  'status' : OrderStatus,
  'timestamp' : Time,
}
export type PaymentMethod = { 'upi' : null } |
  { 'creditCard' : CreditCardInfo } |
  { 'cashOnDelivery' : null } |
  { 'wallet' : null };
export interface Product {
  'id' : ProductId,
  'subCategory' : string,
  'imageUrls' : Array<string>,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'discountPercent' : bigint,
  'variants' : Array<ProductVariant>,
  'stock' : bigint,
  'category' : string,
  'price' : number,
}
export type ProductId = bigint;
export interface ProductVariant {
  'color' : [] | [string],
  'size' : [] | [string],
  'quantity' : bigint,
}
export interface Review {
  'id' : ReviewId,
  'userId' : Principal,
  'date' : Time,
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface ShippingAddress {
  'country' : string,
  'city' : string,
  'name' : string,
  'zipCode' : string,
  'state' : string,
  'address' : string,
  'phone' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wishlist {
  'productIds' : Array<ProductId>,
  'userId' : Principal,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], ProductId>,
  'addReview' : ActorMethod<[ProductId, bigint, string], ReviewId>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[Principal], Cart>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductReviews' : ActorMethod<[ProductId], Array<Review>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'getWishlist' : ActorMethod<[Principal], Wishlist>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [Array<CartItem>, ShippingAddress, PaymentMethod, number],
    OrderId
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[ProductId, Product], undefined>,
  'upgrade' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];